// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ionqzjwgcpkdefefnelb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbnF6andnY3BrZGVmZWZuZWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDMwMTQsImV4cCI6MjA3MDQ3OTAxNH0.D46jB_LiSrW-MZZ241DHAg4HNjHnR6_7Dp1kzT0U5Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});